server:
  port: 9095

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    initialInstanceInfoReplicationIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
    registryFetchIntervalSeconds: 10
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10

ribbon:
  ServerListRefreshInterval: 1000
  eureka:
    enabled: true
