resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      failureRateThreshold: 20
  instances:
    getWeather:
      baseConfig: default
      eventConsumerBufferSize: 10
resilience4j.retry:
  instances:
    getWeather:
      maxRetryAttempts: 3
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 3
      waitDuration: 10
      retryExceptions:
        - java.net.SocketTimeoutException
        - org.springframework.web.client.ResourceAccessException

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 50
      maxWaitDuration: 10ms

com:
  intuit:
    external:
      weather:
        host: api.openweathermap.org
        port: 80
        

restclient:
  timeout: 20