eureka:
  instance:
    nonSecurePort: 8080
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

ribbon:
  eureka:
    enabled: true

logging.level:
  org.springframework.cloud.netflix.ribbon: DEBUG
  com.netflix.loadbalancer: DEBUG

spring:
  cloud:
    services:
      registrationMethod: direct